services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    volumes:
      - ./data:/data
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=${ZINC_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_PASSWORD}
      - ZINC_SERVER_ADDRESS=${HOST}
    ports:
      - '4080:4080'
    
  server:
    build: ./server
    depends_on:
      - zincsearch
    environment:
      - HOST=${HOST}
      - ZINC_USER=${ZINC_USER}
      - ZINC_PASSWORD=${ZINC_PASSWORD}
    ports:
      - '8080:8080'

  client:
    build: ./client
    depends_on:
      - server
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - '5173:5173'

